cutoffs = (
        ' - ',
        '@',
        '(',
        '&',
        'S/E',
        'G/',
        'N/',
        '/',
        '[',
        '1ST FL',
        '-L',
        'LIRR',
        'PT AUTH F',
        '-UNDERGR',
        'UNDERGR',
        '#',
        '-SBWY',
        'SUBWAY',
        '-IN',
        '-STAND',
        'INROCH',
        '-NEWSSTAND',
        '-NEWSTAND',
        '-NEWSTND',
        'NEWSTAND',
        'NEWSSTAND',
        '- STAND',
        '-F',
        '-OUTSIDE',
        '-7TH',
        '-PATH',
        #' BOOTH ',
        ' AND ',
        ' FLR ',
        '-STORE',
        ' NEAR ',
        ' CORNER ',
        '-PORT',
        ' UNIT ',
        ' SPACE ',
        'OUTSIDE',
        ' SHOP ',
        ' STORE ',
        ' LOBBY',
        ' SUITE ',
        ' GROUND ',
        ' KIOSK ',
        ' SIDEWALK ',
        ' MEZZANINE ',
        ' STE ',
        ' BET ',
        'BTWN',
        '%',
        ' WORLD FIN',
        ' LOWER LO',
        ' COR ',
        ' ON ',
        ' MAIN FL',
        ' BOOTH '
        'OPPOSITE',
        ' NO ',
        '2ND FL',
        'SOUTH W',
        'NORTH W',
        'NW',
        ' COR ',
        ' ON ',
        'MOREWOOD PLAZA',
        'DELAWARE PLAZA',
        ' SVC ',
        'BLDG',
        ';',
        ' PO ',
        ' IN ',
        '-NOR',
        '-STU',
        )

replacers = {
        'PLZ':'PLAZA',
        'BROOKLYN TERMINAL MARKET': 'NORTH MARKET STREET',
        'BQE': 'BROOKLYN QUEENS EXPRESSWAY',
        'TPKE': 'TURNPIKE',
        '39ST':'39TH STREET',
        'W.': 'WEST ',
        'BCH':'BEACH',
        'PKWY':'PARKWAY',
        'EXPWY':'EXPRESSWAY',
        'BDWY.':'BROADWAY',
        ' FT ':' FORT ',
        'PENN STA ': 'PENN STATION ',
        'EXWY':'EXPRESSWAY',
        'EXP.':'EXPRESSWAY',
        'VEY4':'VEY',
                }
